name: Mark PR Ready When Ready

on:
  pull_request:
    types: [opened, edited, labeled, unlabeled, synchronize]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  mark-ready:
    name: Mark as ready after successful checks
    runs-on: ubuntu-latest
    permissions:
      checks: read
      contents: write
      pull-requests: write
      statuses: read
    if: |
      contains(github.event.pull_request.labels.*.name, 'Mark Ready When Ready') &&
      github.event.pull_request.draft == true
    steps:
      - name: Mark ready when ready
        uses: kenyonj/mark-ready-when-ready@94be498c0f1b2f36c1b6ce22a1e94f8e9f57b3c1 # v1.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
